version: '2.2'
services:
  zk:
    image: jplock/zookeeper:3.4.13
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.1.0
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_ZOOKEEPER_CONNECT=zk:2181
      - KAFKA_CREATE_TOPICS="test-topic"
    ports:
      - "9092:9092"
      - "7203:7203"

  #producer-delete:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  volumes:
  #    - ./logs:/var/log
  #
